### PR TITLE
Updates for 1.62

### LINKED ISSUE #807: Game was updated to 1.62
Can CET work new game version or should we wait for CET update?

### PR DESCRIPTION
**Pull request by WopsS**
Not tested, but I'm pretty sure it will just work™️. 

Fixes #807.

### CODE REVIEW

**Comment by Thortok** [comment]
I'd be happy to test this if I could figure out how.

**Comment by E3rok** [comment]
https://github.com/WopsS/PerformanceOverhaulCyberpunk/pull/2

I think I found the error for:
`[2023-04-12 01:49:19 UTC+02:00] [error] [Options] [5284] Unsupported game version! Only 1.61 is supported.`

**Comment by psiberx** [comment]
Besides `Image.h` it needs two fixes:
- `RenderContext::pDirectQueue` offset has changed `ED64D8` → `0136D6D8`
```cpp
#pragma once

struct RenderContext
{
    struct Device
    {
        IDXGISwapChain4* pSwapChain;
        uint8_t pad8[0xB0 - 0x8];

    RenderContext() = delete;
    ~RenderContext() = delete;

    static RenderContext* GetInstance() noexcept;

    uint8_t pad0[0xC97F38];
    Device devices[0x30]; // Count unknown, it is at least 0x20
    uint8_t pad[0x136D6D8 - (0xC97F38 + sizeof(devices))];
    ID3D12CommandQueue* pDirectQueue; // 0136D6D8
};

static_assert(sizeof(RenderContext::Device) == 0xB0);
static_assert(offsetof(RenderContext, devices) == 0xC97F38);
static_assert(offsetof(RenderContext, pDirectQueue) == 0x0136D6D8);
```
- Patterns seems correct, but one address isn't for some reason: 
`CScript_AllocateFunction = 0x140284642` should be `0x1401B6070`

**Comment by Thortok** [comment]
The rc1 that psiberx posted on Discord worked for me and for all my CET mods.

Any additional testing I can help with let me know.

**Review by maximegmd — APPROVED** [review]

**Comment by maximegmd** [comment]
I have implemented the changes suggested by psiberx, once the build completes you guys are welcome to give it a shot and let me know if everything works as intended, thanks :)

**Comment by maximegmd** [comment]
https://github.com/maximegmd/CyberEngineTweaks/suites/12180311298/artifacts/643165685

**Comment by dRizzit** [comment]
> https://github.com/maximegmd/CyberEngineTweaks/suites/12180311298/artifacts/643165685

Getting `[error] [Options] [29024] Unsupported game version! Only 1.61 is supported.`  still with that build.

**Comment by ChriZ982** [comment]
@maximegmd same error for me. I also noticed that after the 1.62 patch, there was a smaller patch with just a few megabytes. Did this maybe change the hex values again?

Anyway, the error seems to come from here: https://github.com/maximegmd/CyberEngineTweaks/blob/787a603399659d81ab072cc2d1549cffb0bb61f6/src/Image.h#L7

Should probably be `return std::make_tuple(1, 62);`

**Comment by furryablack** [comment]
> https://github.com/maximegmd/CyberEngineTweaks/suites/12180311298/artifacts/643165685

```
[info] [Options] [16708] Cyber Engine Tweaks is starting...
[info] [Options] [16708] CET version v1.23.0-10-gbf57730 [master]
[info] [Options] [16708] Game version 1.62
info] [Options] [16708] Root path: "C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64"
[info] [Options] [16708] Cyber Engine Tweaks path: "C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks"
[info] [Options] [16708] Lua scripts search path: "C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\mods"
[error] [Options] [16708] Unsupported game version! Only 1.61 is supported.
```

I have same error too

**Comment by ChriZ982** [comment]
> @maximegmd same error for me. I also noticed that after the 1.62 patch, there was a smaller patch with just a few megabytes. Did this maybe change the hex values again?
> 
> Anyway, the error seems to come from here:
> 
> https://github.com/maximegmd/CyberEngineTweaks/blob/787a603399659d81ab072cc2d1549cffb0bb61f6/src/Image.h#L7
> 
> Should probably be `return std::make_tuple(1, 62);`

Sorry, my comment is outdated. This was already fixed on master branch.
This is the latest and correct working version: https://github.com/maximegmd/CyberEngineTweaks/suites/12180835606/artifacts/643193987

**Comment by furryablack** [comment]
> > @maximegmd same error for me. I also noticed that after the 1.62 patch, there was a smaller patch with just a few megabytes. Did this maybe change the hex values again?
> > Anyway, the error seems to come from here:
> > https://github.com/maximegmd/CyberEngineTweaks/blob/787a603399659d81ab072cc2d1549cffb0bb61f6/src/Image.h#L7
> > 
> > Should probably be `return std::make_tuple(1, 62);`
> 
> Sorry, my comment is outdated. This was already fixed on master branch. This is the latest and correct working version: https://github.com/maximegmd/CyberEngineTweaks/suites/12180835606/artifacts/643193987

Get it. And it works for me (I dropped all mods and game and tested it with clear the  1.62 steam version game)

**Comment by furryablack** [comment]
Okey, I have mods

Generic
- Current CET (I use current test artifact from conversation - https://github.com/maximegmd/CyberEngineTweaks/pull/808)

Other generic mods updated to 1.62 already 
- RED4ext (updated for 1.62)
- redscript (updated for 1.62)
- archivexl (updated for 1.62)
- tweakxl (updated for 1.62)

My mods collection
- Missing Persons - Fixer's Hidden Gems
- AI Netrunners Enhanced
- Level Scaling and Balance
- Cyberarms Patch
- Native Settings UI
- System-EX
- Muted Markers
- Mod Settings <-- problem here
- Spicy Clean Hack Screen
- Unequip Mods
- E3 2018 Lighting MOD
- Cybergirls Ads

I can start and play my game (steam) only without Mod Settings mod.
I use that for System-EX mod (https://www.nexusmods.com/cyberpunk2077/mods/3158?tab=description) and I just skip mod settings mod and it works (because System-EX dependency "Mod Settings" is optional)

**Comment by furryablack** [comment]
And I don't have any errors or warnings in log files more.

**Pull request merged**
