### PR TITLE
Enable unity build also for C++

### PR DESCRIPTION
**Pull request by WSSDude**
We had enabled unity builds, but only for C files. This enables it for C++ also, builds should be faster.

### CODE REVIEW

**Comment by maximegmd** [comment]
It's disabled because it doesn't build ^^

**Comment by WSSDude** [comment]
Yeah, cause of RED4ext though it seems... @WopsS please fix 😆

**Comment by maximegmd** [comment]
Should I close this?

**Comment by WSSDude** [comment]
It should be compilable still I believe with those changes, but Im unsure we want them... I would probably close this for now and leave it for another time.

**Pull request closed without merging**
